### ISSUE TITLE
【求助】请问能支持喵崽吗

### ISSUE THREAD

**Issue by Dnyo666** [erzaozi/skland-plugin#1]
感谢大大能够制作云崽的明日方舟插件，因为自己找了很久，amiyabot又用不上群聊。
所以希望大大能够优化一下文档和适配喵版云崽，很感谢，很感谢，毕竟koishi都没有明日方舟插件！

**Comment by CikeyQi** [comment]
这个插件还没弄好，是半成品（

**Comment by CikeyQi** [comment]
寒假这几天可以会弄一下

**Comment by Dnyo666** [comment]
好的，我会持续关注进度的，请问有QQ群聊吗，大大早点睡啦！
