### ISSUE TITLE
遇到了奇怪的bug，消息没反应提示client not online

### ISSUE THREAD

**Issue by LG3418** [erzaozi/skland-plugin#4]
遇到了奇怪的bug，很多消息没反应，不太熟悉云崽所以不太明白报错的原因（
日志如图：
![46f485dca1f0b732e9dffdfc382a7858](https://github.com/erzaozi/skland-plugin/assets/51922165/cf8ab14f-e144-4f98-b2e0-235ff7aaf362)

**Comment by CikeyQi** [comment]
适配器不支持合并转发消息
